import Head from 'next/head';
import Header from '../components/Header';

export default function Home() {
  return (
    <div className="h-screen bg-gray-50">
      <Head>
        <title>Nextagram...🚀</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* 헤더 */}
      <Header />

      {/* 피드 */}

      {/* 모달 */}
    </div>
  );
}
